import type { Puzzle } from './puzzles.js';

/**
 * The seed bank. SPEC §5.4 wants ~200 of these before launch; this is the
 * ~45 needed to play several full games without a repeat.
 *
 * Content rules, in short: read it as a picture, not as a crossword clue;
 * 3-6 emoji; nothing whose rendering falls apart on the worst phone in the room.
 */
export const PUZZLE_BANK: Puzzle[] = [
  // ---------------------------------------------------------------- Film
  { id: 'film-lion-king', lang: 'en', category: 'Film', categoryFull: 'Film · 1994 · animated',
    title: 'The Lion King', emoji: ['🦁', '👑', '🌅'], difficulty: 1 },
  { id: 'film-finding-nemo', lang: 'en', category: 'Film', categoryFull: 'Film · 2003 · animated',
    title: 'Finding Nemo', emoji: ['🔍', '🐠', '🌊'], difficulty: 1 },
  { id: 'film-titanic', lang: 'en', category: 'Film', categoryFull: 'Film · 1997 · romance',
    title: 'Titanic', emoji: ['🚢', '🧊', '💔'], difficulty: 1 },
  { id: 'film-jurassic-park', lang: 'en', category: 'Film', categoryFull: 'Film · 1993 · adventure',
    title: 'Jurassic Park', emoji: ['🦖', '🌴', '🚙'], difficulty: 1 },
  { id: 'film-toy-story', lang: 'en', category: 'Film', categoryFull: 'Film · 1995 · animated',
    title: 'Toy Story', emoji: ['🤠', '🚀', '🧸'], reject: ['toy story 2', 'toy story 3'], difficulty: 1 },
  { id: 'film-frozen', lang: 'en', category: 'Film', categoryFull: 'Film · 2013 · animated',
    title: 'Frozen', emoji: ['❄️', '👭', '🏰'], reject: ['frozen 2'], difficulty: 1 },
  { id: 'film-jaws', lang: 'en', category: 'Film', categoryFull: 'Film · 1975 · thriller',
    title: 'Jaws', emoji: ['🦈', '🏊', '🚤'], difficulty: 1 },
  { id: 'film-home-alone', lang: 'en', category: 'Film', categoryFull: 'Film · 1990 · comedy',
    title: 'Home Alone', emoji: ['🏠', '😱', '👦'], reject: ['home alone 2'], difficulty: 1 },
  { id: 'film-star-wars', lang: 'en', category: 'Film', categoryFull: 'Film · 1977 · space opera',
    title: 'Star Wars', emoji: ['⭐', '⚔️', '🌌'], difficulty: 1 },
  { id: 'film-spiderman', lang: 'en', category: 'Film', categoryFull: 'Film · 2002 · superhero',
    title: 'Spider-Man', aliases: ['spiderman'], reject: ['spider man 2', 'spider man 3'],
    emoji: ['🕷️', '🧑', '🕸️', '🏙️'], difficulty: 1 },
  { id: 'film-back-to-the-future', lang: 'en', category: 'Film', categoryFull: 'Film · 1985 · sci-fi',
    title: 'Back to the Future', emoji: ['🚗', '⏰', '⚡'], difficulty: 2 },
  { id: 'film-the-matrix', lang: 'en', category: 'Film', categoryFull: 'Film · 1999 · sci-fi',
    title: 'The Matrix', emoji: ['💊', '🕶️', '💻', '🐇'], difficulty: 2 },
  { id: 'film-the-godfather', lang: 'en', category: 'Film', categoryFull: 'Film · 1972 · crime',
    title: 'The Godfather', emoji: ['🐴', '🎩', '🍊'], difficulty: 2 },
  { id: 'film-forrest-gump', lang: 'en', category: 'Film', categoryFull: 'Film · 1994 · drama',
    title: 'Forrest Gump', emoji: ['🏃', '🍫', '🪶'], difficulty: 2 },
  { id: 'film-fight-club', lang: 'en', category: 'Film', categoryFull: 'Film · 1999 · drama',
    title: 'Fight Club', emoji: ['👊', '🧼', '🏚️'], difficulty: 2 },
  { id: 'film-inception', lang: 'en', category: 'Film', categoryFull: 'Film · 2010 · sci-fi',
    title: 'Inception', emoji: ['🌀', '💤', '🏙️', '🌀'], difficulty: 3 },
  { id: 'film-interstellar', lang: 'en', category: 'Film', categoryFull: 'Film · 2014 · sci-fi',
    title: 'Interstellar', emoji: ['🚀', '🌌', '⏳', '🌽'], difficulty: 3 },
  { id: 'film-parasite', lang: 'en', category: 'Film', categoryFull: 'Film · 2019 · thriller',
    title: 'Parasite', emoji: ['🇰🇷', '🏠', '🪳', '🌧️'], difficulty: 3 },
  { id: 'film-silence-lambs', lang: 'en', category: 'Film', categoryFull: 'Film · 1991 · thriller',
    title: 'The Silence of the Lambs', aliases: ['silence of the lambs'],
    emoji: ['🤫', '🐑', '🦋'], difficulty: 3 },

  // ---------------------------------------------------------------- TV
  { id: 'tv-game-of-thrones', lang: 'en', category: 'TV', categoryFull: 'TV · 2011 · fantasy',
    title: 'Game of Thrones', aliases: ['got'], emoji: ['🐉', '⚔️', '🪑', '❄️'], difficulty: 1 },
  { id: 'tv-squid-game', lang: 'en', category: 'TV', categoryFull: 'TV · 2021 · thriller',
    title: 'Squid Game', emoji: ['🦑', '🔴', '🟢', '💰'], difficulty: 1 },
  { id: 'tv-breaking-bad', lang: 'en', category: 'TV', categoryFull: 'TV · 2008 · crime',
    title: 'Breaking Bad', emoji: ['🧪', '🎩', '🚐', '💵'], difficulty: 2 },
  { id: 'tv-stranger-things', lang: 'en', category: 'TV', categoryFull: 'TV · 2016 · sci-fi',
    title: 'Stranger Things', emoji: ['🚲', '🔦', '🧇', '🙃'], difficulty: 2 },
  { id: 'tv-the-office', lang: 'en', category: 'TV', categoryFull: 'TV · 2005 · comedy',
    title: 'The Office', emoji: ['🏢', '📎', '😬', '🎥'], difficulty: 2 },
  { id: 'tv-friends', lang: 'en', category: 'TV', categoryFull: 'TV · 1994 · comedy',
    title: 'Friends', emoji: ['☕', '🛋️', '🏙️', '🦆'], difficulty: 2 },
  { id: 'tv-black-mirror', lang: 'en', category: 'TV', categoryFull: 'TV · 2011 · sci-fi',
    title: 'Black Mirror', emoji: ['⬛', '🪞', '📱'], difficulty: 3 },

  // ---------------------------------------------------------------- Song
  { id: 'song-purple-rain', lang: 'en', category: 'Song', categoryFull: 'Song · 1984 · Prince',
    title: 'Purple Rain', emoji: ['💜', '🌧️'], difficulty: 1 },
  { id: 'song-dancing-queen', lang: 'en', category: 'Song', categoryFull: 'Song · 1976 · ABBA',
    title: 'Dancing Queen', emoji: ['💃', '👑', '🕺'], difficulty: 1 },
  { id: 'song-yellow-submarine', lang: 'en', category: 'Song', categoryFull: 'Song · 1966 · The Beatles',
    title: 'Yellow Submarine', emoji: ['💛', '🛥️', '🌊'], difficulty: 1 },
  { id: 'song-old-town-road', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · Lil Nas X',
    title: 'Old Town Road', emoji: ['🤠', '🐴', '🛣️'], difficulty: 2 },
  { id: 'song-blinding-lights', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · The Weeknd',
    title: 'Blinding Lights', emoji: ['😎', '💡', '🚗', '🌃'], difficulty: 2 },
  { id: 'song-bad-guy', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · Billie Eilish',
    title: 'Bad Guy', emoji: ['😈', '🙋', '🖤'], difficulty: 2 },
  { id: 'song-sweet-child', lang: 'en', category: 'Song', categoryFull: "Song · 1987 · Guns N' Roses",
    title: "Sweet Child o' Mine", aliases: ['sweet child of mine'], emoji: ['🍬', '👶', '🌹'], difficulty: 3 },
  { id: 'song-teen-spirit', lang: 'en', category: 'Song', categoryFull: 'Song · 1991 · Nirvana',
    title: 'Smells Like Teen Spirit', emoji: ['👃', '🧑‍🎤', '👻'], difficulty: 3 },
  { id: 'song-rolling-deep', lang: 'en', category: 'Song', categoryFull: 'Song · 2010 · Adele',
    title: 'Rolling in the Deep', emoji: ['🎲', '🌊', '💔'], difficulty: 3 },

  // ---------------------------------------------------------------- Book
  { id: 'book-alice', lang: 'en', category: 'Book', categoryFull: 'Book · 1865 · Lewis Carroll',
    title: 'Alice in Wonderland', aliases: ["alice's adventures in wonderland"],
    emoji: ['👧', '🐇', '🕳️', '🫖'], difficulty: 1 },
  { id: 'book-romeo-juliet', lang: 'en', category: 'Book', categoryFull: 'Play · 1597 · Shakespeare',
    title: 'Romeo and Juliet', emoji: ['👦', '❤️', '👧', '⚰️'], difficulty: 1 },
  { id: 'book-lotr', lang: 'en', category: 'Book', categoryFull: 'Book · 1954 · Tolkien',
    title: 'The Lord of the Rings', aliases: ['lord of the rings', 'lotr'],
    emoji: ['💍', '🌋', '🧝'], difficulty: 2 },
  { id: 'book-hunger-games', lang: 'en', category: 'Book', categoryFull: 'Book · 2008 · Suzanne Collins',
    title: 'The Hunger Games', emoji: ['🏹', '🔥', '🕊️'], difficulty: 2 },
  { id: 'book-little-prince', lang: 'en', category: 'Book', categoryFull: 'Book · 1943 · Saint-Exupéry',
    title: 'The Little Prince', emoji: ['👑', '👦', '🌹', '🪐'], difficulty: 2 },
  { id: 'book-moby-dick', lang: 'en', category: 'Book', categoryFull: 'Book · 1851 · Melville',
    title: 'Moby-Dick', aliases: ['moby dick'], emoji: ['🐋', '⛵', '🗡️'], difficulty: 3 },

  // ---------------------------------------------------------------- Game
  { id: 'game-minecraft', lang: 'en', category: 'Game', categoryFull: 'Game · 2011 · sandbox',
    title: 'Minecraft', emoji: ['⛏️', '🟩', '🧱'], difficulty: 1 },
  { id: 'game-pac-man', lang: 'en', category: 'Game', categoryFull: 'Game · 1980 · arcade',
    title: 'Pac-Man', aliases: ['pacman'], emoji: ['🟡', '👻', '🍒'], difficulty: 1 },
  { id: 'game-angry-birds', lang: 'en', category: 'Game', categoryFull: 'Game · 2009 · mobile',
    title: 'Angry Birds', emoji: ['😠', '🐦', '🐷'], difficulty: 1 },
  { id: 'game-super-mario', lang: 'en', category: 'Game', categoryFull: 'Game · 1985 · platformer',
    title: 'Super Mario Bros', aliases: ['super mario brothers', 'super mario'],
    emoji: ['🍄', '🔧', '🐢', '🏰'], difficulty: 1 },
  { id: 'game-among-us', lang: 'en', category: 'Game', categoryFull: 'Game · 2018 · party',
    title: 'Among Us', emoji: ['🚀', '🔪', '🟥', '❓'], difficulty: 2 },
  { id: 'game-tetris', lang: 'en', category: 'Game', categoryFull: 'Game · 1984 · puzzle',
    title: 'Tetris', emoji: ['🟦', '🟨', '⬇️', '🧱'], difficulty: 2 },

  // ---------------------------------------------------------------- Phrase
  { id: 'phrase-couch-potato', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · lazy',
    title: 'Couch potato', emoji: ['🛋️', '🥔'], difficulty: 1 },
  { id: 'phrase-cats-and-dogs', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · weather',
    title: 'Raining cats and dogs', emoji: ['🌧️', '🐱', '🐶'], difficulty: 1 },
  { id: 'phrase-piece-of-cake', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · easy',
    title: 'Piece of cake', emoji: ['🧩', '🍰'], difficulty: 2 },
  { id: 'phrase-break-a-leg', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · good luck',
    title: 'Break a leg', emoji: ['🦵', '💥', '🎭'], difficulty: 2 },
  { id: 'phrase-spill-the-beans', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · secrets',
    title: 'Spill the beans', emoji: ['🫗', '🫘', '🤫'], difficulty: 2 },
  { id: 'phrase-when-pigs-fly', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · never',
    title: 'When pigs fly', emoji: ['🐷', '✈️', '🚫'], difficulty: 2 },
  { id: 'phrase-blue-moon', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · rarely',
    title: 'Once in a blue moon', emoji: ['1️⃣', '🔵', '🌙'], difficulty: 3 },
  { id: 'phrase-netflix-and-chill', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2014 · internet',
    title: 'Netflix and chill', emoji: ['📺', '🍿', '😌'], difficulty: 2 },
  { id: 'meme-rickroll', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2007 · bait and switch',
    title: 'Rickroll', aliases: ['rick roll', 'rickrolled', 'never gonna give you up'],
    emoji: ['🕺', '🎤', '🔗', '😑'], difficulty: 3 },
];
