import type { Puzzle } from './puzzles.js';

/**
 * The bank. SPEC §5.4 wants ~200 before launch; this is 220, which is enough
 * that a regular group meets a repeat rarely rather than every other game.
 *
 * Content rules, in short: read it as a picture, not as a crossword clue;
 * 2-4 emoji; nothing whose rendering falls apart on the worst phone in the room.
 *
 * `validatePuzzles()` in puzzles.ts is the gate, and test/puzzles.test.ts runs it:
 * ids unique, no two puzzles answerable by the same normalized string, every
 * `reject` within a few edits of its own answer, and every clue a real emoji
 * sequence rather than text in disguise.
 */
export const PUZZLE_BANK: Puzzle[] = [
  // ---------------------------------------------------------------- Film
  { id: 'film-lion-king', lang: 'en', category: 'Film', categoryFull: 'Film · 1994 · animated',
    title: 'The Lion King', emoji: ['🦁', '👑', '🌅'], difficulty: 1 },
  { id: 'film-finding-nemo', lang: 'en', category: 'Film', categoryFull: 'Film · 2003 · animated',
    title: 'Finding Nemo', emoji: ['🔍', '🐠', '🌊'], difficulty: 1 },
  { id: 'film-titanic', lang: 'en', category: 'Film', categoryFull: 'Film · 1997 · romance',
    title: 'Titanic', emoji: ['🚢', '🧊', '💔'], difficulty: 1 },
  { id: 'film-jurassic-park', lang: 'en', category: 'Film', categoryFull: 'Film · 1993 · adventure',
    title: 'Jurassic Park', emoji: ['🦖', '🌴', '🚙'], difficulty: 1 },
  { id: 'film-toy-story', lang: 'en', category: 'Film', categoryFull: 'Film · 1995 · animated',
    title: 'Toy Story', emoji: ['🤠', '🚀', '🧸'], reject: ['toy story 2', 'toy story 3'], difficulty: 1 },
  { id: 'film-frozen', lang: 'en', category: 'Film', categoryFull: 'Film · 2013 · animated',
    title: 'Frozen', emoji: ['❄️', '👭', '🏰'], reject: ['frozen 2'], difficulty: 1 },
  { id: 'film-jaws', lang: 'en', category: 'Film', categoryFull: 'Film · 1975 · thriller',
    title: 'Jaws', emoji: ['🦈', '🏊', '🚤'], difficulty: 1 },
  { id: 'film-home-alone', lang: 'en', category: 'Film', categoryFull: 'Film · 1990 · comedy',
    title: 'Home Alone', emoji: ['🏠', '😱', '👦'], reject: ['home alone 2'], difficulty: 1 },
  { id: 'film-star-wars', lang: 'en', category: 'Film', categoryFull: 'Film · 1977 · space opera',
    title: 'Star Wars', emoji: ['⭐', '⚔️', '🌌'], difficulty: 1 },
  { id: 'film-spiderman', lang: 'en', category: 'Film', categoryFull: 'Film · 2002 · superhero',
    title: 'Spider-Man', aliases: ['spiderman'], reject: ['spider man 2', 'spider man 3'],
    emoji: ['🕷️', '🧑', '🕸️', '🏙️'], difficulty: 1 },
  { id: 'film-back-to-the-future', lang: 'en', category: 'Film', categoryFull: 'Film · 1985 · sci-fi',
    title: 'Back to the Future', emoji: ['🚗', '⏰', '⚡'], difficulty: 2 },
  { id: 'film-the-matrix', lang: 'en', category: 'Film', categoryFull: 'Film · 1999 · sci-fi',
    title: 'The Matrix', emoji: ['💊', '🕶️', '💻', '🐇'], difficulty: 2 },
  { id: 'film-the-godfather', lang: 'en', category: 'Film', categoryFull: 'Film · 1972 · crime',
    title: 'The Godfather', emoji: ['🐴', '🎩', '🍊'], difficulty: 2 },
  { id: 'film-forrest-gump', lang: 'en', category: 'Film', categoryFull: 'Film · 1994 · drama',
    title: 'Forrest Gump', emoji: ['🏃', '🍫', '🪶'], difficulty: 2 },
  { id: 'film-fight-club', lang: 'en', category: 'Film', categoryFull: 'Film · 1999 · drama',
    title: 'Fight Club', emoji: ['👊', '🧼', '🏚️'], difficulty: 2 },
  { id: 'film-inception', lang: 'en', category: 'Film', categoryFull: 'Film · 2010 · sci-fi',
    title: 'Inception', emoji: ['🌀', '💤', '🏙️', '🌀'], difficulty: 3 },
  { id: 'film-interstellar', lang: 'en', category: 'Film', categoryFull: 'Film · 2014 · sci-fi',
    title: 'Interstellar', emoji: ['🚀', '🌌', '⏳', '🌽'], difficulty: 3 },
  { id: 'film-parasite', lang: 'en', category: 'Film', categoryFull: 'Film · 2019 · thriller',
    title: 'Parasite', emoji: ['🇰🇷', '🏠', '🪳', '🌧️'], difficulty: 3 },
  { id: 'film-silence-lambs', lang: 'en', category: 'Film', categoryFull: 'Film · 1991 · thriller',
    title: 'The Silence of the Lambs', aliases: ['silence of the lambs'],
    emoji: ['🤫', '🐑', '🦋'], difficulty: 3 },

  // ---------------------------------------------------------------- TV
  { id: 'tv-game-of-thrones', lang: 'en', category: 'TV', categoryFull: 'TV · 2011 · fantasy',
    title: 'Game of Thrones', aliases: ['got'], emoji: ['🐉', '⚔️', '🪑', '❄️'], difficulty: 1 },
  { id: 'tv-squid-game', lang: 'en', category: 'TV', categoryFull: 'TV · 2021 · thriller',
    title: 'Squid Game', emoji: ['🦑', '🔴', '🟢', '💰'], difficulty: 1 },
  { id: 'tv-breaking-bad', lang: 'en', category: 'TV', categoryFull: 'TV · 2008 · crime',
    title: 'Breaking Bad', emoji: ['🧪', '🎩', '🚐', '💵'], difficulty: 2 },
  { id: 'tv-stranger-things', lang: 'en', category: 'TV', categoryFull: 'TV · 2016 · sci-fi',
    title: 'Stranger Things', emoji: ['🚲', '🔦', '🧇', '🙃'], difficulty: 2 },
  { id: 'tv-the-office', lang: 'en', category: 'TV', categoryFull: 'TV · 2005 · comedy',
    title: 'The Office', emoji: ['🏢', '📎', '😬', '🎥'], difficulty: 2 },
  { id: 'tv-friends', lang: 'en', category: 'TV', categoryFull: 'TV · 1994 · comedy',
    title: 'Friends', emoji: ['☕', '🛋️', '🏙️', '🦆'], difficulty: 2 },
  { id: 'tv-black-mirror', lang: 'en', category: 'TV', categoryFull: 'TV · 2011 · sci-fi',
    title: 'Black Mirror', emoji: ['⬛', '🪞', '📱'], difficulty: 3 },

  // ---------------------------------------------------------------- Song
  { id: 'song-purple-rain', lang: 'en', category: 'Song', categoryFull: 'Song · 1984 · Prince',
    title: 'Purple Rain', emoji: ['💜', '🌧️'], difficulty: 1 },
  { id: 'song-dancing-queen', lang: 'en', category: 'Song', categoryFull: 'Song · 1976 · ABBA',
    title: 'Dancing Queen', emoji: ['💃', '👑', '🕺'], difficulty: 1 },
  { id: 'song-yellow-submarine', lang: 'en', category: 'Song', categoryFull: 'Song · 1966 · The Beatles',
    title: 'Yellow Submarine', emoji: ['💛', '🛥️', '🌊'], difficulty: 1 },
  { id: 'song-old-town-road', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · Lil Nas X',
    title: 'Old Town Road', emoji: ['🤠', '🐴', '🛣️'], difficulty: 2 },
  { id: 'song-blinding-lights', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · The Weeknd',
    title: 'Blinding Lights', emoji: ['😎', '💡', '🚗', '🌃'], difficulty: 2 },
  { id: 'song-bad-guy', lang: 'en', category: 'Song', categoryFull: 'Song · 2019 · Billie Eilish',
    title: 'Bad Guy', emoji: ['😈', '🙋', '🖤'], difficulty: 2 },
  { id: 'song-sweet-child', lang: 'en', category: 'Song', categoryFull: "Song · 1987 · Guns N' Roses",
    title: "Sweet Child o' Mine", aliases: ['sweet child of mine'], emoji: ['🍬', '👶', '🌹'], difficulty: 3 },
  { id: 'song-teen-spirit', lang: 'en', category: 'Song', categoryFull: 'Song · 1991 · Nirvana',
    title: 'Smells Like Teen Spirit', emoji: ['👃', '🧑‍🎤', '👻'], difficulty: 3 },
  { id: 'song-rolling-deep', lang: 'en', category: 'Song', categoryFull: 'Song · 2010 · Adele',
    title: 'Rolling in the Deep', emoji: ['🎲', '🌊', '💔'], difficulty: 3 },

  // ---------------------------------------------------------------- Book
  { id: 'book-alice', lang: 'en', category: 'Book', categoryFull: 'Book · 1865 · Lewis Carroll',
    title: 'Alice in Wonderland', aliases: ["alice's adventures in wonderland"],
    emoji: ['👧', '🐇', '🕳️', '🫖'], difficulty: 1 },
  { id: 'book-romeo-juliet', lang: 'en', category: 'Book', categoryFull: 'Play · 1597 · Shakespeare',
    title: 'Romeo and Juliet', emoji: ['👦', '❤️', '👧', '⚰️'], difficulty: 1 },
  { id: 'book-lotr', lang: 'en', category: 'Book', categoryFull: 'Book · 1954 · Tolkien',
    title: 'The Lord of the Rings', aliases: ['lord of the rings', 'lotr'],
    emoji: ['💍', '🌋', '🧝'], difficulty: 2 },
  { id: 'book-hunger-games', lang: 'en', category: 'Book', categoryFull: 'Book · 2008 · Suzanne Collins',
    title: 'The Hunger Games', emoji: ['🏹', '🔥', '🕊️'], difficulty: 2 },
  { id: 'book-little-prince', lang: 'en', category: 'Book', categoryFull: 'Book · 1943 · Saint-Exupéry',
    title: 'The Little Prince', emoji: ['👑', '👦', '🌹', '🪐'], difficulty: 2 },
  { id: 'book-moby-dick', lang: 'en', category: 'Book', categoryFull: 'Book · 1851 · Melville',
    title: 'Moby-Dick', aliases: ['moby dick'], emoji: ['🐋', '⛵', '🗡️'], difficulty: 3 },

  // ---------------------------------------------------------------- Game
  { id: 'game-minecraft', lang: 'en', category: 'Game', categoryFull: 'Game · 2011 · sandbox',
    title: 'Minecraft', emoji: ['⛏️', '🟩', '🧱'], difficulty: 1 },
  { id: 'game-pac-man', lang: 'en', category: 'Game', categoryFull: 'Game · 1980 · arcade',
    title: 'Pac-Man', aliases: ['pacman'], emoji: ['🟡', '👻', '🍒'], difficulty: 1 },
  { id: 'game-angry-birds', lang: 'en', category: 'Game', categoryFull: 'Game · 2009 · mobile',
    title: 'Angry Birds', emoji: ['😠', '🐦', '🐷'], difficulty: 1 },
  { id: 'game-super-mario', lang: 'en', category: 'Game', categoryFull: 'Game · 1985 · platformer',
    title: 'Super Mario Bros', aliases: ['super mario brothers', 'super mario'],
    emoji: ['🍄', '🔧', '🐢', '🏰'], difficulty: 1 },
  { id: 'game-among-us', lang: 'en', category: 'Game', categoryFull: 'Game · 2018 · party',
    title: 'Among Us', emoji: ['🚀', '🔪', '🟥', '❓'], difficulty: 2 },
  { id: 'game-tetris', lang: 'en', category: 'Game', categoryFull: 'Game · 1984 · puzzle',
    title: 'Tetris', emoji: ['🟦', '🟨', '⬇️', '🧱'], difficulty: 2 },

  // ---------------------------------------------------------------- Phrase
  { id: 'phrase-couch-potato', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · lazy',
    title: 'Couch potato', emoji: ['🛋️', '🥔'], difficulty: 1 },
  { id: 'phrase-cats-and-dogs', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · weather',
    title: 'Raining cats and dogs', emoji: ['🌧️', '🐱', '🐶'], difficulty: 1 },
  { id: 'phrase-piece-of-cake', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · easy',
    title: 'Piece of cake', emoji: ['🧩', '🍰'], difficulty: 2 },
  { id: 'phrase-break-a-leg', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · good luck',
    title: 'Break a leg', emoji: ['🦵', '💥', '🎭'], difficulty: 2 },
  { id: 'phrase-spill-the-beans', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · secrets',
    title: 'Spill the beans', emoji: ['🫗', '🫘', '🤫'], difficulty: 2 },
  { id: 'phrase-when-pigs-fly', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · never',
    title: 'When pigs fly', emoji: ['🐷', '✈️', '🚫'], difficulty: 2 },
  { id: 'phrase-blue-moon', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · rarely',
    title: 'Once in a blue moon', emoji: ['1️⃣', '🔵', '🌙'], difficulty: 3 },
  { id: 'phrase-netflix-and-chill', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2014 · internet',
    title: 'Netflix and chill', emoji: ['📺', '🍿', '😌'], difficulty: 2 },
  { id: 'meme-rickroll', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2007 · bait and switch',
    title: 'Rickroll', aliases: ['rick roll', 'rickrolled', 'never gonna give you up'],
    emoji: ['🕺', '🎤', '🔗', '😑'], difficulty: 3 },

  // -------------------------------------------------------------- Film
  { id: 'film-wizard-of-oz', lang: 'en', category: 'Film', categoryFull: 'Film · 1939 · musical',
    title: 'The Wizard of Oz', aliases: ['wizard of oz'],
    emoji: ['🌪️', '🏠', '👠', '🦁'], difficulty: 2 },
  { id: 'film-et', lang: 'en', category: 'Film', categoryFull: 'Film · 1982 · sci-fi',
    title: 'E.T. the Extra-Terrestrial', aliases: ['ET', 'E.T.'],
    emoji: ['👽', '🚲', '🌕'], difficulty: 2 },
  { id: 'film-the-shining', lang: 'en', category: 'Film', categoryFull: 'Film · 1980 · horror',
    title: 'The Shining', emoji: ['🏨', '🪓', '🚪', '🩸'], difficulty: 2 },
  { id: 'film-pulp-fiction', lang: 'en', category: 'Film', categoryFull: 'Film · 1994 · crime',
    title: 'Pulp Fiction', emoji: ['🍔', '💉', '💃', '🔫'], difficulty: 3 },
  { id: 'film-up', lang: 'en', category: 'Film', categoryFull: 'Film · 2009 · animated',
    title: 'Up', emoji: ['🏠', '🎈', '👴'], difficulty: 2 },
  { id: 'film-ratatouille', lang: 'en', category: 'Film', categoryFull: 'Film · 2007 · animated',
    title: 'Ratatouille', emoji: ['🐀', '👨‍🍳', '🍲', '🗼'], difficulty: 2 },
  { id: 'film-shrek', lang: 'en', category: 'Film', categoryFull: 'Film · 2001 · animated',
    title: 'Shrek', reject: ['shrek 2'], emoji: ['👹', '🐴', '🏰', '💚'], difficulty: 1 },
  { id: 'film-the-incredibles', lang: 'en', category: 'Film', categoryFull: 'Film · 2004 · animated',
    title: 'The Incredibles', emoji: ['🦸', '👨‍👩‍👧‍👦', '🎭'], difficulty: 2 },
  { id: 'film-despicable-me', lang: 'en', category: 'Film', categoryFull: 'Film · 2010 · animated',
    title: 'Despicable Me', emoji: ['🦹', '🍌', '🌙'], difficulty: 2 },
  { id: 'film-coco', lang: 'en', category: 'Film', categoryFull: 'Film · 2017 · animated',
    title: 'Coco', emoji: ['💀', '🎸', '🇲🇽', '🌼'], difficulty: 2 },
  { id: 'film-moana', lang: 'en', category: 'Film', categoryFull: 'Film · 2016 · animated',
    title: 'Moana', emoji: ['🌊', '🛶', '🌺'], difficulty: 1 },
  { id: 'film-cars', lang: 'en', category: 'Film', categoryFull: 'Film · 2006 · animated',
    title: 'Cars', emoji: ['🚗', '🏁', '⚡'], difficulty: 1 },
  { id: 'film-aladdin', lang: 'en', category: 'Film', categoryFull: 'Film · 1992 · animated',
    title: 'Aladdin', emoji: ['🧞', '🪔', '🐒'], difficulty: 1 },
  { id: 'film-the-terminator', lang: 'en', category: 'Film', categoryFull: 'Film · 1984 · sci-fi',
    title: 'The Terminator', aliases: ['terminator'], emoji: ['🤖', '🔫', '🕶️'], difficulty: 2 },
  { id: 'film-alien', lang: 'en', category: 'Film', categoryFull: 'Film · 1979 · horror',
    title: 'Alien', reject: ['aliens'], emoji: ['👽', '🚀', '🥚', '😱'], difficulty: 2 },
  { id: 'film-rocky', lang: 'en', category: 'Film', categoryFull: 'Film · 1976 · sport',
    title: 'Rocky', emoji: ['🥊', '🪜', '🇺🇸'], difficulty: 2 },
  { id: 'film-gladiator', lang: 'en', category: 'Film', categoryFull: 'Film · 2000 · epic',
    title: 'Gladiator', emoji: ['🗡️', '🏟️', '🦁'], difficulty: 2 },
  { id: 'film-cast-away', lang: 'en', category: 'Film', categoryFull: 'Film · 2000 · drama',
    title: 'Cast Away', aliases: ['castaway'], emoji: ['🏝️', '🏐', '✈️'], difficulty: 2 },
  { id: 'film-la-la-land', lang: 'en', category: 'Film', categoryFull: 'Film · 2016 · musical',
    title: 'La La Land', emoji: ['💃', '🎹', '🌃', '🎬'], difficulty: 2 },
  { id: 'film-men-in-black', lang: 'en', category: 'Film', categoryFull: 'Film · 1997 · sci-fi',
    title: 'Men in Black', emoji: ['🕴️', '🕶️', '👽'], difficulty: 2 },
  { id: 'film-the-truman-show', lang: 'en', category: 'Film', categoryFull: 'Film · 1998 · drama',
    title: 'The Truman Show', emoji: ['📺', '🏝️', '🎬'], difficulty: 3 },
  { id: 'film-jumanji', lang: 'en', category: 'Film', categoryFull: 'Film · 1995 · adventure',
    title: 'Jumanji', emoji: ['🎲', '🐘', '🌴', '🥁'], difficulty: 2 },

  // ---------------------------------------------------------------- TV
  { id: 'tv-the-simpsons', lang: 'en', category: 'TV', categoryFull: 'TV · 1989 · animated',
    title: 'The Simpsons', emoji: ['🟡', '🍩', '🛹'], difficulty: 1 },
  { id: 'tv-spongebob', lang: 'en', category: 'TV', categoryFull: 'TV · 1999 · animated',
    title: 'SpongeBob SquarePants', aliases: ['spongebob'], emoji: ['🧽', '🍍', '🌊'], difficulty: 1 },
  { id: 'tv-the-crown', lang: 'en', category: 'TV', categoryFull: 'TV · 2016 · drama',
    title: 'The Crown', emoji: ['👑', '🇬🇧', '🐕'], difficulty: 2 },
  { id: 'tv-peaky-blinders', lang: 'en', category: 'TV', categoryFull: 'TV · 2013 · crime',
    title: 'Peaky Blinders', emoji: ['🎩', '🔪', '🏭'], difficulty: 3 },
  { id: 'tv-the-walking-dead', lang: 'en', category: 'TV', categoryFull: 'TV · 2010 · horror',
    title: 'The Walking Dead', emoji: ['🧟', '🚶', '🏚️'], difficulty: 2 },
  { id: 'tv-money-heist', lang: 'en', category: 'TV', categoryFull: 'TV · 2017 · thriller',
    title: 'Money Heist', aliases: ['la casa de papel'], emoji: ['🎭', '💰', '🇪🇸'], difficulty: 2 },
  { id: 'tv-sherlock', lang: 'en', category: 'TV', categoryFull: 'TV · 2010 · crime',
    title: 'Sherlock', emoji: ['🔍', '🎻', '🎩'], difficulty: 2 },
  { id: 'tv-chernobyl', lang: 'en', category: 'TV', categoryFull: 'TV · 2019 · drama',
    title: 'Chernobyl', emoji: ['☢️', '🏭', '🔥'], difficulty: 3 },
  { id: 'tv-the-mandalorian', lang: 'en', category: 'TV', categoryFull: 'TV · 2019 · sci-fi',
    title: 'The Mandalorian', emoji: ['🪖', '🚀', '👶'], difficulty: 3 },
  { id: 'tv-rick-and-morty', lang: 'en', category: 'TV', categoryFull: 'TV · 2013 · animated',
    title: 'Rick and Morty', emoji: ['👨‍🔬', '👦', '🛸'], difficulty: 2 },
  { id: 'tv-lost', lang: 'en', category: 'TV', categoryFull: 'TV · 2004 · mystery',
    title: 'Lost', emoji: ['🏝️', '✈️', '🔢'], difficulty: 2 },
  { id: 'tv-narcos', lang: 'en', category: 'TV', categoryFull: 'TV · 2015 · crime',
    title: 'Narcos', emoji: ['🇨🇴', '💊', '👮'], difficulty: 3 },
  { id: 'tv-better-call-saul', lang: 'en', category: 'TV', categoryFull: 'TV · 2015 · crime',
    title: 'Better Call Saul', emoji: ['⚖️', '📞', '🕴️'], difficulty: 3 },
  { id: 'tv-big-bang-theory', lang: 'en', category: 'TV', categoryFull: 'TV · 2007 · sitcom',
    title: 'The Big Bang Theory', emoji: ['💥', '🔬', '🤓'], difficulty: 2 },

  // -------------------------------------------------------------- Song
  { id: 'song-bohemian-rhapsody', lang: 'en', category: 'Song', categoryFull: 'Song · 1975 · Queen',
    title: 'Bohemian Rhapsody', emoji: ['🎭', '👑', '🎸', '⚡'], difficulty: 2 },
  { id: 'song-hotel-california', lang: 'en', category: 'Song', categoryFull: 'Song · 1976 · Eagles',
    title: 'Hotel California', emoji: ['🏨', '🌴', '🎸'], difficulty: 2 },
  { id: 'song-imagine', lang: 'en', category: 'Song', categoryFull: 'Song · 1971 · John Lennon',
    title: 'Imagine', emoji: ['🕊️', '🌍', '🎹'], difficulty: 2 },
  { id: 'song-hey-jude', lang: 'en', category: 'Song', categoryFull: 'Song · 1968 · The Beatles',
    title: 'Hey Jude', emoji: ['👋', '🧑', '🎸'], difficulty: 2 },
  { id: 'song-thriller', lang: 'en', category: 'Song', categoryFull: 'Song · 1982 · Michael Jackson',
    title: 'Thriller', emoji: ['🧟', '🕺', '🌙'], difficulty: 1 },
  { id: 'song-billie-jean', lang: 'en', category: 'Song', categoryFull: 'Song · 1983 · Michael Jackson',
    title: 'Billie Jean', emoji: ['👖', '💫', '🕺'], difficulty: 2 },
  { id: 'song-stairway-to-heaven', lang: 'en', category: 'Song', categoryFull: 'Song · 1971 · Led Zeppelin',
    title: 'Stairway to Heaven', emoji: ['🪜', '☁️', '🎸'], difficulty: 2 },
  { id: 'song-wonderwall', lang: 'en', category: 'Song', categoryFull: 'Song · 1995 · Oasis',
    title: 'Wonderwall', emoji: ['🧱', '🌟', '🎸'], difficulty: 2 },
  { id: 'song-shape-of-you', lang: 'en', category: 'Song', categoryFull: 'Song · 2017 · Ed Sheeran',
    title: 'Shape of You', emoji: ['📐', '👤', '🎤'], difficulty: 2 },
  { id: 'song-umbrella', lang: 'en', category: 'Song', categoryFull: 'Song · 2007 · Rihanna',
    title: 'Umbrella', emoji: ['☂️', '🌧️', '🎤'], difficulty: 1 },
  { id: 'song-firework', lang: 'en', category: 'Song', categoryFull: 'Song · 2010 · Katy Perry',
    title: 'Firework', emoji: ['🎆', '✨', '🎤'], difficulty: 1 },
  { id: 'song-happy', lang: 'en', category: 'Song', categoryFull: 'Song · 2013 · Pharrell',
    title: 'Happy', emoji: ['😀', '👏', '🎶'], difficulty: 1 },
  { id: 'song-bad-romance', lang: 'en', category: 'Song', categoryFull: 'Song · 2009 · Lady Gaga',
    title: 'Bad Romance', emoji: ['💔', '🌹', '🎤'], difficulty: 2 },
  { id: 'song-despacito', lang: 'en', category: 'Song', categoryFull: 'Song · 2017 · Luis Fonsi',
    title: 'Despacito', emoji: ['🐌', '🇵🇷', '🎶'], difficulty: 2 },
  { id: 'song-gangnam-style', lang: 'en', category: 'Song', categoryFull: 'Song · 2012 · PSY',
    title: 'Gangnam Style', emoji: ['🐴', '🕺', '🇰🇷'], difficulty: 1 },
  { id: 'song-uptown-funk', lang: 'en', category: 'Song', categoryFull: 'Song · 2014 · Mark Ronson',
    title: 'Uptown Funk', emoji: ['🏙️', '🕺', '🎺'], difficulty: 2 },

  // -------------------------------------------------------------- Book
  { id: 'book-harry-potter', lang: 'en', category: 'Book', categoryFull: 'Book · 1997 · fantasy',
    title: 'Harry Potter', reject: ['harry potter 2'], emoji: ['⚡', '🧙', '👓', '🪄'], difficulty: 1 },
  { id: 'book-the-hobbit', lang: 'en', category: 'Book', categoryFull: 'Book · 1937 · fantasy',
    title: 'The Hobbit', emoji: ['🏡', '🐉', '💎'], difficulty: 2 },
  { id: 'book-pride-and-prejudice', lang: 'en', category: 'Book', categoryFull: 'Book · 1813 · romance',
    title: 'Pride and Prejudice', emoji: ['💃', '🎩', '💍'], difficulty: 3 },
  { id: 'book-great-gatsby', lang: 'en', category: 'Book', categoryFull: 'Book · 1925 · classic',
    title: 'The Great Gatsby', emoji: ['🥂', '🎩', '💚'], difficulty: 3 },
  { id: 'book-dracula', lang: 'en', category: 'Book', categoryFull: 'Book · 1897 · gothic',
    title: 'Dracula', emoji: ['🧛', '🦇', '🏰'], difficulty: 1 },
  { id: 'book-frankenstein', lang: 'en', category: 'Book', categoryFull: 'Book · 1818 · gothic',
    title: 'Frankenstein', emoji: ['🧟', '⚡', '🔬'], difficulty: 1 },
  { id: 'book-jungle-book', lang: 'en', category: 'Book', categoryFull: 'Book · 1894 · adventure',
    title: 'The Jungle Book', emoji: ['🐻', '🐍', '🌴', '👦'], difficulty: 2 },
  { id: 'book-charlottes-web', lang: 'en', category: 'Book', categoryFull: 'Book · 1952 · children',
    title: 'Charlotte’s Web', aliases: ['charlottes web'], emoji: ['🕷️', '🕸️', '🐷'], difficulty: 2 },
  { id: 'book-matilda', lang: 'en', category: 'Book', categoryFull: 'Book · 1988 · children',
    title: 'Matilda', emoji: ['👧', '📚', '✨'], difficulty: 2 },
  { id: 'book-cat-in-the-hat', lang: 'en', category: 'Book', categoryFull: 'Book · 1957 · children',
    title: 'The Cat in the Hat', emoji: ['🐱', '🎩', '📕'], difficulty: 2 },
  { id: 'book-treasure-island', lang: 'en', category: 'Book', categoryFull: 'Book · 1883 · adventure',
    title: 'Treasure Island', emoji: ['🏴‍☠️', '🗺️', '💰'], difficulty: 2 },
  { id: 'book-don-quixote', lang: 'en', category: 'Book', categoryFull: 'Book · 1605 · classic',
    title: 'Don Quixote', emoji: ['🐴', '🌬️', '⚔️'], difficulty: 3 },
  { id: 'book-1984', lang: 'en', category: 'Book', categoryFull: 'Book · 1949 · dystopia',
    title: 'Nineteen Eighty-Four', aliases: ['1984'], emoji: ['👁️', '📺', '🚫'], difficulty: 3 },
  { id: 'book-da-vinci-code', lang: 'en', category: 'Book', categoryFull: 'Book · 2003 · thriller',
    title: 'The Da Vinci Code', emoji: ['🖼️', '🔍', '✝️'], difficulty: 3 },
  { id: 'book-peter-pan', lang: 'en', category: 'Book', categoryFull: 'Book · 1911 · children',
    title: 'Peter Pan', emoji: ['🧚', '👦', '🐊'], difficulty: 1 },
  { id: 'book-hungry-caterpillar', lang: 'en', category: 'Book', categoryFull: 'Book · 1969 · children',
    title: 'The Very Hungry Caterpillar', emoji: ['🐛', '🍎', '🦋'], difficulty: 2 },
  { id: 'book-old-man-and-the-sea', lang: 'en', category: 'Book', categoryFull: 'Book · 1952 · classic',
    title: 'The Old Man and the Sea', emoji: ['👴', '🎣', '🌊'], difficulty: 3 },

  // -------------------------------------------------------------- Game
  { id: 'game-zelda', lang: 'en', category: 'Game', categoryFull: 'Game · 1986 · adventure',
    title: 'The Legend of Zelda', aliases: ['zelda'], emoji: ['🗡️', '🛡️', '🧝'], difficulty: 2 },
  { id: 'game-sonic', lang: 'en', category: 'Game', categoryFull: 'Game · 1991 · platformer',
    title: 'Sonic the Hedgehog', aliases: ['sonic'], emoji: ['💙', '🦔', '💨'], difficulty: 1 },
  { id: 'game-fortnite', lang: 'en', category: 'Game', categoryFull: 'Game · 2017 · battle royale',
    title: 'Fortnite', emoji: ['🪂', '🔫', '🏗️'], difficulty: 1 },
  { id: 'game-candy-crush', lang: 'en', category: 'Game', categoryFull: 'Game · 2012 · puzzle',
    title: 'Candy Crush', emoji: ['🍬', '💥', '📱'], difficulty: 1 },
  { id: 'game-call-of-duty', lang: 'en', category: 'Game', categoryFull: 'Game · 2003 · shooter',
    title: 'Call of Duty', emoji: ['📞', '🎖️', '🔫'], difficulty: 2 },
  { id: 'game-the-sims', lang: 'en', category: 'Game', categoryFull: 'Game · 2000 · life sim',
    title: 'The Sims', emoji: ['👨‍👩‍👧', '🏠', '💎'], difficulty: 2 },
  { id: 'game-pokemon', lang: 'en', category: 'Game', categoryFull: 'Game · 1996 · RPG',
    title: 'Pokemon', emoji: ['⚡', '🐭', '🔴'], difficulty: 1 },
  { id: 'game-animal-crossing', lang: 'en', category: 'Game', categoryFull: 'Game · 2001 · life sim',
    title: 'Animal Crossing', emoji: ['🦝', '🏝️', '🌸'], difficulty: 2 },
  { id: 'game-gta', lang: 'en', category: 'Game', categoryFull: 'Game · 1997 · open world',
    title: 'Grand Theft Auto', aliases: ['gta'], emoji: ['🚗', '💰', '🔫'], difficulty: 2 },
  { id: 'game-street-fighter', lang: 'en', category: 'Game', categoryFull: 'Game · 1987 · fighting',
    title: 'Street Fighter', emoji: ['👊', '🥋', '🌪️'], difficulty: 2 },
  { id: 'game-space-invaders', lang: 'en', category: 'Game', categoryFull: 'Game · 1978 · arcade',
    title: 'Space Invaders', emoji: ['👾', '🚀', '🕹️'], difficulty: 2 },
  { id: 'game-donkey-kong', lang: 'en', category: 'Game', categoryFull: 'Game · 1981 · arcade',
    title: 'Donkey Kong', emoji: ['🦍', '🛢️', '🪜'], difficulty: 2 },
  { id: 'game-portal', lang: 'en', category: 'Game', categoryFull: 'Game · 2007 · puzzle',
    title: 'Portal', emoji: ['🌀', '🔫', '🍰'], difficulty: 3 },

  // ------------------------------------------------------------ Phrase
  { id: 'phrase-bite-the-bullet', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · endure',
    title: 'Bite the bullet', emoji: ['😬', '🦷', '🔫'], difficulty: 2 },
  { id: 'phrase-under-the-weather', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · unwell',
    title: 'Under the weather', emoji: ['⬇️', '🌦️', '🤒'], difficulty: 2 },
  { id: 'phrase-arm-and-a-leg', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · expensive',
    title: 'Cost an arm and a leg', emoji: ['💪', '🦵', '💰'], difficulty: 2 },
  { id: 'phrase-two-birds-one-stone', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · efficient',
    title: 'Kill two birds with one stone', emoji: ['🐦', '🐦', '🪨'], difficulty: 3 },
  { id: 'phrase-cat-out-of-the-bag', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · secrets',
    title: 'Let the cat out of the bag', emoji: ['🐱', '⬆️', '🎒'], difficulty: 2 },
  { id: 'phrase-nail-on-the-head', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · exactly right',
    title: 'Hit the nail on the head', emoji: ['🔨', '📍', '💯'], difficulty: 3 },
  { id: 'phrase-blessing-in-disguise', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · luck',
    title: 'A blessing in disguise', emoji: ['🙏', '🎭'], difficulty: 3 },
  { id: 'phrase-speak-of-the-devil', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · timing',
    title: 'Speak of the devil', emoji: ['🗣️', '😈'], difficulty: 2 },
  { id: 'phrase-midnight-oil', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · working late',
    title: 'Burn the midnight oil', emoji: ['🔥', '🕛', '🛢️'], difficulty: 3 },
  { id: 'phrase-wrong-tree', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · mistaken',
    title: 'Barking up the wrong tree', emoji: ['🐶', '🌳', '❌'], difficulty: 2 },
  { id: 'phrase-spilled-milk', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · regret',
    title: 'Cry over spilled milk', aliases: ['cry over spilt milk'],
    emoji: ['😭', '🥛', '💦'], difficulty: 2 },
  { id: 'phrase-silver-lining', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · optimism',
    title: 'Every cloud has a silver lining', emoji: ['☁️', '🥈', '✨'], difficulty: 3 },
  { id: 'phrase-extra-mile', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · effort',
    title: 'Go the extra mile', emoji: ['➕', '🏃', '📏'], difficulty: 3 },
  { id: 'phrase-hold-your-horses', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · wait',
    title: 'Hold your horses', emoji: ['✋', '🐴', '🐴'], difficulty: 2 },
  { id: 'phrase-cut-to-the-chase', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · get to the point',
    title: 'Cut to the chase', emoji: ['✂️', '🏃', '💨'], difficulty: 2 },
  { id: 'phrase-bury-the-hatchet', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · make peace',
    title: 'Bury the hatchet', emoji: ['⚰️', '🪓', '🕊️'], difficulty: 3 },
  { id: 'phrase-throw-in-the-towel', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · give up',
    title: 'Throw in the towel', emoji: ['🤲', '🧺', '🥊'], difficulty: 2 },
  { id: 'phrase-break-the-ice', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · social',
    title: 'Break the ice', emoji: ['🔨', '🧊'], difficulty: 1 },
  { id: 'phrase-cloud-nine', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · delighted',
    title: 'On cloud nine', emoji: ['☁️', '9️⃣', '😊'], difficulty: 2 },
  { id: 'phrase-cold-feet', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · nervous',
    title: 'Cold feet', emoji: ['🥶', '🦶'], difficulty: 1 },
  { id: 'phrase-bring-home-the-bacon', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · earning',
    title: 'Bring home the bacon', emoji: ['🏠', '🥓', '💰'], difficulty: 2 },
  { id: 'phrase-early-bird', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · promptness',
    title: 'The early bird catches the worm', emoji: ['🌅', '🐦', '🪱'], difficulty: 3 },
  { id: 'phrase-time-flies', lang: 'en', category: 'Phrase', categoryFull: 'Phrase · idiom · time',
    title: 'Time flies', emoji: ['⏰', '🕊️'], difficulty: 2 },

  // -------------------------------------------------------------- Meme
  { id: 'meme-doge', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2013 · internet',
    title: 'Doge', emoji: ['🐕', '🌕', '💰'], difficulty: 2 },
  { id: 'meme-distracted-boyfriend', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2017 · stock photo',
    title: 'Distracted boyfriend', emoji: ['👫', '👀', '👩'], difficulty: 3 },
  { id: 'meme-this-is-fine', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2013 · webcomic',
    title: 'This is fine', emoji: ['🔥', '🐶', '☕'], difficulty: 2 },
  { id: 'meme-grumpy-cat', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2012 · internet',
    title: 'Grumpy Cat', emoji: ['😾', '🐱', '👎'], difficulty: 2 },
  { id: 'meme-ice-bucket', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2014 · charity',
    title: 'Ice Bucket Challenge', emoji: ['🧊', '🪣', '🥶'], difficulty: 2 },
  { id: 'meme-harlem-shake', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2013 · dance',
    title: 'Harlem Shake', emoji: ['🕺', '🎧', '💥'], difficulty: 3 },
  { id: 'meme-deal-with-it', lang: 'en', category: 'Meme', categoryFull: 'Meme · 2010 · internet',
    title: 'Deal with it', emoji: ['😎', '🕶️', '👌'], difficulty: 3 },

  // -------------------------------------------------------------- Food
  { id: 'food-fish-and-chips', lang: 'en', category: 'Food', categoryFull: 'Food · dish · British',
    title: 'Fish and chips', emoji: ['🐟', '🍟', '🇬🇧'], difficulty: 1 },
  { id: 'food-spaghetti-bolognese', lang: 'en', category: 'Food', categoryFull: 'Food · dish · Italian',
    title: 'Spaghetti bolognese', emoji: ['🍝', '🥩', '🇮🇹'], difficulty: 1 },
  { id: 'food-apple-pie', lang: 'en', category: 'Food', categoryFull: 'Food · dessert · baked',
    title: 'Apple pie', emoji: ['🍎', '🥧'], difficulty: 1 },
  { id: 'food-sushi', lang: 'en', category: 'Food', categoryFull: 'Food · dish · Japanese',
    title: 'Sushi', emoji: ['🍣', '🐟', '🇯🇵'], difficulty: 1 },
  { id: 'food-fried-chicken', lang: 'en', category: 'Food', categoryFull: 'Food · dish · fried',
    title: 'Fried chicken', emoji: ['🍗', '🔥'], difficulty: 1 },
  { id: 'food-pancakes', lang: 'en', category: 'Food', categoryFull: 'Food · breakfast · sweet',
    title: 'Pancakes', aliases: ['pancake'], emoji: ['🥞', '🍯'], difficulty: 1 },
  { id: 'food-garlic-bread', lang: 'en', category: 'Food', categoryFull: 'Food · side · baked',
    title: 'Garlic bread', emoji: ['🧄', '🍞'], difficulty: 1 },
  { id: 'food-hot-dog', lang: 'en', category: 'Food', categoryFull: 'Food · street food · grilled',
    title: 'Hot dog', emoji: ['🌭', '🔥'], difficulty: 1 },
  { id: 'food-banana-split', lang: 'en', category: 'Food', categoryFull: 'Food · dessert · frozen',
    title: 'Banana split', emoji: ['🍌', '✂️', '🍨'], difficulty: 2 },
  { id: 'food-fortune-cookie', lang: 'en', category: 'Food', categoryFull: 'Food · dessert · baked',
    title: 'Fortune cookie', emoji: ['🥠', '🔮'], difficulty: 2 },
  { id: 'food-guacamole', lang: 'en', category: 'Food', categoryFull: 'Food · dip · Mexican',
    title: 'Guacamole', emoji: ['🥑', '🥣', '🇲🇽'], difficulty: 2 },
  { id: 'food-croissant', lang: 'en', category: 'Food', categoryFull: 'Food · breakfast · French',
    title: 'Croissant', emoji: ['🥐', '☕', '🇫🇷'], difficulty: 1 },

  // ------------------------------------------------------------- Place
  { id: 'place-eiffel-tower', lang: 'en', category: 'Place', categoryFull: 'Place · Paris · landmark',
    title: 'The Eiffel Tower', aliases: ['eiffel tower'], emoji: ['🗼', '🇫🇷', '💡'], difficulty: 1 },
  { id: 'place-great-wall', lang: 'en', category: 'Place', categoryFull: 'Place · China · landmark',
    title: 'The Great Wall of China', aliases: ['great wall of china', 'great wall'],
    emoji: ['🧱', '🇨🇳', '🐉'], difficulty: 1 },
  { id: 'place-statue-of-liberty', lang: 'en', category: 'Place', categoryFull: 'Place · New York · landmark',
    title: 'The Statue of Liberty', aliases: ['statue of liberty'],
    emoji: ['🗽', '🇺🇸', '🔥'], difficulty: 1 },
  { id: 'place-big-ben', lang: 'en', category: 'Place', categoryFull: 'Place · London · landmark',
    title: 'Big Ben', emoji: ['🕰️', '🇬🇧', '🗼'], difficulty: 2 },
  { id: 'place-pyramids-of-giza', lang: 'en', category: 'Place', categoryFull: 'Place · Egypt · landmark',
    title: 'The Pyramids of Giza', aliases: ['pyramids of giza', 'the pyramids'],
    emoji: ['🔺', '🇪🇬', '🐪'], difficulty: 2 },
  { id: 'place-venice', lang: 'en', category: 'Place', categoryFull: 'Place · Italy · city',
    title: 'Venice', emoji: ['🛶', '🌊', '🇮🇹'], difficulty: 2 },
  { id: 'place-mount-everest', lang: 'en', category: 'Place', categoryFull: 'Place · Nepal · mountain',
    title: 'Mount Everest', emoji: ['🏔️', '🇳🇵', '🧗'], difficulty: 2 },
  { id: 'place-niagara-falls', lang: 'en', category: 'Place', categoryFull: 'Place · Canada · waterfall',
    title: 'Niagara Falls', emoji: ['💦', '🍁', '🚤'], difficulty: 2 },
  { id: 'place-grand-canyon', lang: 'en', category: 'Place', categoryFull: 'Place · Arizona · canyon',
    title: 'The Grand Canyon', aliases: ['grand canyon'], emoji: ['🏜️', '🇺🇸', '🦅'], difficulty: 2 },
  { id: 'place-stonehenge', lang: 'en', category: 'Place', categoryFull: 'Place · England · monument',
    title: 'Stonehenge', emoji: ['🪨', '🪨', '🇬🇧'], difficulty: 2 },
  { id: 'place-taj-mahal', lang: 'en', category: 'Place', categoryFull: 'Place · India · landmark',
    title: 'The Taj Mahal', aliases: ['taj mahal'], emoji: ['🕌', '🇮🇳', '💎'], difficulty: 2 },
  { id: 'place-hollywood', lang: 'en', category: 'Place', categoryFull: 'Place · Los Angeles · district',
    title: 'Hollywood', emoji: ['🎬', '⭐', '🌴'], difficulty: 1 },

  // ------------------------------------------------------------- Sport
  { id: 'sport-formula-one', lang: 'en', category: 'Sport', categoryFull: 'Sport · motorsport · racing',
    title: 'Formula One', aliases: ['f1', 'formula 1'], emoji: ['🏎️', '🏁', '🏆'], difficulty: 1 },
  { id: 'sport-world-cup', lang: 'en', category: 'Sport', categoryFull: 'Sport · football · tournament',
    title: 'The World Cup', aliases: ['world cup'], emoji: ['🏆', '⚽', '🌍'], difficulty: 1 },
  { id: 'sport-marathon', lang: 'en', category: 'Sport', categoryFull: 'Sport · athletics · endurance',
    title: 'Marathon', emoji: ['🏃', '📏', '🥇'], difficulty: 2 },
  { id: 'sport-olympics', lang: 'en', category: 'Sport', categoryFull: 'Sport · multi-sport · global',
    title: 'The Olympic Games', aliases: ['olympics', 'olympic games'],
    emoji: ['🥇', '🔥', '🌍'], difficulty: 1 },
  { id: 'sport-tour-de-france', lang: 'en', category: 'Sport', categoryFull: 'Sport · cycling · stage race',
    title: 'The Tour de France', aliases: ['tour de france'],
    emoji: ['🚴', '🇫🇷', '🏔️'], difficulty: 2 },
  { id: 'sport-wimbledon', lang: 'en', category: 'Sport', categoryFull: 'Sport · tennis · tournament',
    title: 'Wimbledon', emoji: ['🎾', '🍓', '🇬🇧'], difficulty: 2 },
  { id: 'sport-super-bowl', lang: 'en', category: 'Sport', categoryFull: 'Sport · American football · final',
    title: 'The Super Bowl', aliases: ['super bowl'], emoji: ['🏈', '🏆', '🎤'], difficulty: 2 },
  { id: 'sport-ice-hockey', lang: 'en', category: 'Sport', categoryFull: 'Sport · team sport · winter',
    title: 'Ice hockey', emoji: ['🏒', '🧊', '🥅'], difficulty: 1 },
  { id: 'sport-scuba-diving', lang: 'en', category: 'Sport', categoryFull: 'Sport · water sport · underwater',
    title: 'Scuba diving', emoji: ['🤿', '🐠', '🌊'], difficulty: 1 },

  // -------------------------------------------------------- Fairy tale
  { id: 'tale-cinderella', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Perrault',
    title: 'Cinderella', emoji: ['👠', '🎃', '🕛'], difficulty: 1 },
  { id: 'tale-red-riding-hood', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Grimm',
    title: 'Little Red Riding Hood', aliases: ['red riding hood'],
    emoji: ['🔴', '🧥', '🐺', '🧺'], difficulty: 1 },
  { id: 'tale-snow-white', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Grimm',
    title: 'Snow White', emoji: ['❄️', '🍎', '7️⃣'], difficulty: 1 },
  { id: 'tale-three-little-pigs', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · fable',
    title: 'The Three Little Pigs', aliases: ['three little pigs'],
    emoji: ['3️⃣', '🐷', '🏠'], difficulty: 1 },
  { id: 'tale-goldilocks', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · English',
    title: 'Goldilocks', emoji: ['👧', '🐻', '🥣'], difficulty: 2 },
  { id: 'tale-hansel-and-gretel', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Grimm',
    title: 'Hansel and Gretel', emoji: ['👦', '👧', '🍬', '🏠'], difficulty: 2 },
  { id: 'tale-ugly-duckling', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Andersen',
    title: 'The Ugly Duckling', aliases: ['ugly duckling'], emoji: ['🦆', '🦢', '😢'], difficulty: 2 },
  { id: 'tale-rapunzel', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Grimm',
    title: 'Rapunzel', emoji: ['👩', '💇', '🏰'], difficulty: 2 },
  { id: 'tale-jack-and-the-beanstalk', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · English',
    title: 'Jack and the Beanstalk', emoji: ['👦', '🫘', '🌱'], difficulty: 2 },
  { id: 'tale-little-mermaid', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Andersen',
    title: 'The Little Mermaid', aliases: ['little mermaid'], emoji: ['🧜', '🐚', '🌊'], difficulty: 1 },
  { id: 'tale-sleeping-beauty', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Perrault',
    title: 'Sleeping Beauty', emoji: ['😴', '👸', '🌹'], difficulty: 1 },
  { id: 'tale-pinocchio', lang: 'en', category: 'Fairy tale', categoryFull: 'Fairy tale · folk · Collodi',
    title: 'Pinocchio', emoji: ['🪵', '👦', '👃'], difficulty: 1 },

  // ----------------------------------------------------------- Holiday
  { id: 'holiday-christmas', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · December · winter',
    title: 'Christmas', emoji: ['🎄', '🎅', '🎁'], difficulty: 1 },
  { id: 'holiday-halloween', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · October · autumn',
    title: 'Halloween', emoji: ['🎃', '👻', '🍬'], difficulty: 1 },
  { id: 'holiday-valentines', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · February · romance',
    title: 'Valentine’s Day', aliases: ['valentines day'], emoji: ['💌', '❤️', '🌹'], difficulty: 1 },
  { id: 'holiday-new-years-eve', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · December · celebration',
    title: 'New Year’s Eve', aliases: ['new years eve'], emoji: ['🎉', '🕛', '🥂'], difficulty: 1 },
  { id: 'holiday-easter', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · spring · Christian',
    title: 'Easter', emoji: ['🐰', '🥚', '🌷'], difficulty: 1 },
  { id: 'holiday-thanksgiving', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · November · harvest',
    title: 'Thanksgiving', emoji: ['🦃', '🥧', '🙏'], difficulty: 1 },
  { id: 'holiday-diwali', lang: 'en', category: 'Holiday', categoryFull: 'Holiday · autumn · festival of lights',
    title: 'Diwali', emoji: ['🪔', '✨', '🇮🇳'], difficulty: 2 },
];
